
import React from 'react';
import { AlertTriangle, Shield } from 'lucide-react';

const Disclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="py-20 relative">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <span className="inline-block px-3 py-1 bg-sophia-blue/20 text-sophia-blue rounded-full text-sm mb-4 flex items-center justify-center mx-auto">
            <AlertTriangle className="w-4 h-4 mr-1" />
            Legal Information
          </span>
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-display mb-6">
            Legal <span className="text-gradient">Disclaimer</span>
          </h2>
          <p className="text-lg text-white/80 max-w-3xl mx-auto">
            Important information about the use of Sophia Aeterna
          </p>
        </div>

        <div className="max-w-4xl mx-auto glass-panel rounded-xl p-8 border border-white/10">
          <div className="mb-8 flex items-center justify-center">
            <div className="w-16 h-16 bg-sophia-purple/10 rounded-full flex items-center justify-center">
              <Shield className="w-8 h-8 text-sophia-purple" />
            </div>
          </div>

          <div className="space-y-6 text-white/80">
            <p>
              <strong className="text-white">DISCLAIMER:</strong> Sophia Aeterna is an AI tool designed to provide information and guidance related to philosophy, spirituality, and esoteric traditions. It is important to understand the following:
            </p>

            <h3 className="text-xl font-display text-white mt-6">Nature of Content</h3>
            <p>
              The content provided by Sophia Aeterna is for informational and educational purposes only. It represents philosophical and spiritual perspectives inspired by the work of Manly P. Hall but is generated by an AI system and does not constitute the actual words or direct teachings of Manly P. Hall himself.
            </p>

            <h3 className="text-xl font-display text-white mt-6">Not Professional Advice</h3>
            <p>
              Sophia Aeterna does not provide medical, legal, financial, psychological, or professional advice. Users should not rely on this tool for making important personal decisions. If you require professional advice, please consult with qualified human professionals in the relevant field.
            </p>

            <h3 className="text-xl font-display text-white mt-6">Limitation of Liability</h3>
            <p>
              AI Web Tools LLC, its owners, employees, and affiliates make no warranties, expressed or implied, and hereby disclaim all liability for any loss or damage arising from the use of Sophia Aeterna. By using this tool, you agree that your use is at your own risk.
            </p>

            <h3 className="text-xl font-display text-white mt-6">Historical and Factual Accuracy</h3>
            <p>
              While efforts are made to ensure accuracy, the information provided may contain errors or inaccuracies. Users are encouraged to verify any historical or factual claims through additional research from reliable sources.
            </p>

            <h3 className="text-xl font-display text-white mt-6">Religious and Spiritual Content</h3>
            <p>
              Sophia Aeterna discusses various religious and spiritual traditions from a philosophical perspective. It is not affiliated with any specific religious organization and does not advocate for any particular religious belief system. Its purpose is educational and contemplative rather than proselytizing.
            </p>

            <h3 className="text-xl font-display text-white mt-6">User Responsibility</h3>
            <p>
              Users are responsible for their own interpretations and applications of the information provided. AI Web Tools LLC is not responsible for any actions taken based on interactions with Sophia Aeterna.
            </p>

            <p className="mt-8 text-sm text-white/60">
              By using Sophia Aeterna, you acknowledge that you have read, understood, and agree to these terms and conditions. If you do not agree with these terms, please refrain from using this tool.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
